/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PromotedPurchaseImageRelationshipsPromotedPurchase } from './PromotedPurchaseImageRelationshipsPromotedPurchase';
import {
    PromotedPurchaseImageRelationshipsPromotedPurchaseFromJSON,
    PromotedPurchaseImageRelationshipsPromotedPurchaseFromJSONTyped,
    PromotedPurchaseImageRelationshipsPromotedPurchaseToJSON,
} from './PromotedPurchaseImageRelationshipsPromotedPurchase';

/**
 * 
 * @export
 * @interface PromotedPurchaseImageRelationships
 */
export interface PromotedPurchaseImageRelationships {
    /**
     * 
     * @type {PromotedPurchaseImageRelationshipsPromotedPurchase}
     * @memberof PromotedPurchaseImageRelationships
     */
    promotedPurchase?: PromotedPurchaseImageRelationshipsPromotedPurchase;
}

/**
 * Check if a given object implements the PromotedPurchaseImageRelationships interface.
 */
export function instanceOfPromotedPurchaseImageRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PromotedPurchaseImageRelationshipsFromJSON(json: any): PromotedPurchaseImageRelationships {
    return PromotedPurchaseImageRelationshipsFromJSONTyped(json, false);
}

export function PromotedPurchaseImageRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotedPurchaseImageRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'promotedPurchase': !exists(json, 'promotedPurchase') ? undefined : PromotedPurchaseImageRelationshipsPromotedPurchaseFromJSON(json['promotedPurchase']),
    };
}

export function PromotedPurchaseImageRelationshipsToJSON(value?: PromotedPurchaseImageRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'promotedPurchase': PromotedPurchaseImageRelationshipsPromotedPurchaseToJSON(value.promotedPurchase),
    };
}

