/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppRelationshipsPromotedPurchasesDataInner } from './AppRelationshipsPromotedPurchasesDataInner';
import {
    AppRelationshipsPromotedPurchasesDataInnerFromJSON,
    AppRelationshipsPromotedPurchasesDataInnerFromJSONTyped,
    AppRelationshipsPromotedPurchasesDataInnerToJSON,
} from './AppRelationshipsPromotedPurchasesDataInner';

/**
 * 
 * @export
 * @interface PromotedPurchaseImageRelationshipsPromotedPurchase
 */
export interface PromotedPurchaseImageRelationshipsPromotedPurchase {
    /**
     * 
     * @type {AppRelationshipsPromotedPurchasesDataInner}
     * @memberof PromotedPurchaseImageRelationshipsPromotedPurchase
     */
    data?: AppRelationshipsPromotedPurchasesDataInner;
}

/**
 * Check if a given object implements the PromotedPurchaseImageRelationshipsPromotedPurchase interface.
 */
export function instanceOfPromotedPurchaseImageRelationshipsPromotedPurchase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PromotedPurchaseImageRelationshipsPromotedPurchaseFromJSON(json: any): PromotedPurchaseImageRelationshipsPromotedPurchase {
    return PromotedPurchaseImageRelationshipsPromotedPurchaseFromJSONTyped(json, false);
}

export function PromotedPurchaseImageRelationshipsPromotedPurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotedPurchaseImageRelationshipsPromotedPurchase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : AppRelationshipsPromotedPurchasesDataInnerFromJSON(json['data']),
    };
}

export function PromotedPurchaseImageRelationshipsPromotedPurchaseToJSON(value?: PromotedPurchaseImageRelationshipsPromotedPurchase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AppRelationshipsPromotedPurchasesDataInnerToJSON(value.data),
    };
}

