/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlternativeDistributionKeyCreateRequestDataRelationshipsApp } from './AlternativeDistributionKeyCreateRequestDataRelationshipsApp';
import {
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppFromJSON,
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppFromJSONTyped,
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppToJSON,
} from './AlternativeDistributionKeyCreateRequestDataRelationshipsApp';
import type { AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion } from './AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion';
import {
    AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersionFromJSON,
    AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersionFromJSONTyped,
    AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersionToJSON,
} from './AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion';
import type { ReviewSubmissionRelationshipsItems } from './ReviewSubmissionRelationshipsItems';
import {
    ReviewSubmissionRelationshipsItemsFromJSON,
    ReviewSubmissionRelationshipsItemsFromJSONTyped,
    ReviewSubmissionRelationshipsItemsToJSON,
} from './ReviewSubmissionRelationshipsItems';
import type { ReviewSubmissionRelationshipsSubmittedByActor } from './ReviewSubmissionRelationshipsSubmittedByActor';
import {
    ReviewSubmissionRelationshipsSubmittedByActorFromJSON,
    ReviewSubmissionRelationshipsSubmittedByActorFromJSONTyped,
    ReviewSubmissionRelationshipsSubmittedByActorToJSON,
} from './ReviewSubmissionRelationshipsSubmittedByActor';

/**
 * 
 * @export
 * @interface ReviewSubmissionRelationships
 */
export interface ReviewSubmissionRelationships {
    /**
     * 
     * @type {AlternativeDistributionKeyCreateRequestDataRelationshipsApp}
     * @memberof ReviewSubmissionRelationships
     */
    app?: AlternativeDistributionKeyCreateRequestDataRelationshipsApp;
    /**
     * 
     * @type {ReviewSubmissionRelationshipsItems}
     * @memberof ReviewSubmissionRelationships
     */
    items?: ReviewSubmissionRelationshipsItems;
    /**
     * 
     * @type {AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion}
     * @memberof ReviewSubmissionRelationships
     */
    appStoreVersionForReview?: AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion;
    /**
     * 
     * @type {ReviewSubmissionRelationshipsSubmittedByActor}
     * @memberof ReviewSubmissionRelationships
     */
    submittedByActor?: ReviewSubmissionRelationshipsSubmittedByActor;
    /**
     * 
     * @type {ReviewSubmissionRelationshipsSubmittedByActor}
     * @memberof ReviewSubmissionRelationships
     */
    lastUpdatedByActor?: ReviewSubmissionRelationshipsSubmittedByActor;
}

/**
 * Check if a given object implements the ReviewSubmissionRelationships interface.
 */
export function instanceOfReviewSubmissionRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReviewSubmissionRelationshipsFromJSON(json: any): ReviewSubmissionRelationships {
    return ReviewSubmissionRelationshipsFromJSONTyped(json, false);
}

export function ReviewSubmissionRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewSubmissionRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': !exists(json, 'app') ? undefined : AlternativeDistributionKeyCreateRequestDataRelationshipsAppFromJSON(json['app']),
        'items': !exists(json, 'items') ? undefined : ReviewSubmissionRelationshipsItemsFromJSON(json['items']),
        'appStoreVersionForReview': !exists(json, 'appStoreVersionForReview') ? undefined : AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersionFromJSON(json['appStoreVersionForReview']),
        'submittedByActor': !exists(json, 'submittedByActor') ? undefined : ReviewSubmissionRelationshipsSubmittedByActorFromJSON(json['submittedByActor']),
        'lastUpdatedByActor': !exists(json, 'lastUpdatedByActor') ? undefined : ReviewSubmissionRelationshipsSubmittedByActorFromJSON(json['lastUpdatedByActor']),
    };
}

export function ReviewSubmissionRelationshipsToJSON(value?: ReviewSubmissionRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AlternativeDistributionKeyCreateRequestDataRelationshipsAppToJSON(value.app),
        'items': ReviewSubmissionRelationshipsItemsToJSON(value.items),
        'appStoreVersionForReview': AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersionToJSON(value.appStoreVersionForReview),
        'submittedByActor': ReviewSubmissionRelationshipsSubmittedByActorToJSON(value.submittedByActor),
        'lastUpdatedByActor': ReviewSubmissionRelationshipsSubmittedByActorToJSON(value.lastUpdatedByActor),
    };
}

